# _config.yml
title: "Documentation de NUMMU Bot"
description: "Guide complet d'utilisation et de développement du bot NUMMU"
baseurl: "/docs"       # chemin relatif au site
url: "https://votre-domaine.com"  # URL de base du site
theme: minima
markdown: kramdown

# Navigation principale (optionnel)
collections:
  sections:
    output: true
